name: BuildPlugin
on:
  push:
    branches: [ci]
jobs:
  macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Grab FST
        run: |
          mkdir FST
          cd FST
          curl -O https://git.iem.at/zmoelnig/FST/-/archive/master/FST-master.zip
          unzip FST-master.zip
          mv FST-master pluginterfaces
          mv pluginterfaces/fst pluginterfaces/vst2.x
          echo "Hello Steinberg, if you don't like this, please bring back discrete loudspeaker layouts."
      - name: Build that thing
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DVST2PATH="FST/"
          make
      - name: Zip it
        run:  zip -r ABComparison_macOS.zip  build/ABComparison_artefacts/Release/VST/ABComparison.vst
      - uses: actions/upload-artifact@v1
        with:
          name: ABComparison_macOS
          path: ABComparison_macOS.zip
